### ISSUE TITLE
Is the checked in code compiled?

### ISSUE THREAD

**Issue by husafan** [spchuang/fb-local-chat-bot#3]
Love the library - thanks for putting it together!

I was curious - is the checked in JS under /build run through the babel-cli? Looking at the output of one of my own projects, I noticed that the '_interopRequireDefault' and '_createClass' methods in index.js look to be the same as the methods in JS generated by the babel-cli.

I wanted to send some pull requests your way, but don't want to make changes to generated code.

Thanks!

**Comment by spchuang** [comment]
yeah everything in build/ is compiled. For source, look at https://github.com/spchuang/fb-local-chat-bot/tree/master/src

**Comment by husafan** [comment]
Doh.. Sorry man. I completely missed that folder. Thank you!
